version: '3.9'
name: focus-service

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: "focus"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "zilant116"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      TZ: Europe/Moscow
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d
      - focus-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d focus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
      
  backend:
    build: ./focus
    container_name: focus-back
    restart: on-failure
    volumes:
      - ./focus:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Moscow

  redis:
    image: redis:latest
    container_name: focus-redis
    environment:
      - REDIS_PASSWORD=zilant116
      - TZ=Europe/Moscow
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass zilant116" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "zilant116", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
    container_name: focus-front
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
      


volumes:
  focus-data:
